# Generated by Django 3.2.19 on 2023-07-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description_en', models.CharField(max_length=1024)),
                ('description_pt', models.CharField(max_length=1024)),
                ('log_path', models.CharField(max_length=512)),
                ('sugested_inputs', models.CharField(max_length=26)),
                ('eta', models.FloatField()),
                ('is_diffusion', models.BooleanField(default=False)),
                ('aux_diff_path', models.CharField(default=None, max_length=512, null=True)),
                ('diff_path', models.CharField(default=None, max_length=512, null=True)),
            ],
        ),
    ]
